---
galaxy_info:
  author: Caleb Woods
  description: Install Ruby with Brightbox PPA
  company: RoleModel
  license: MIT
  min_ansible_version: 1.9

  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
  categories:
    - system
    - development

dependencies: []
