# Installations on all hosts
---
- name: Update APT sources
  apt: update_cache=yes

- name: Install essential software
  apt: name={{ item.package }}
  with_items:
    - {package: build-essential}
    - {package: ntp}
    - {package: git}
    - {package: vim}
    - {package: emacs24}
