# Installations on all hosts
---
- name: Update APT sources
  apt: update_cache=yes

- name: Install essential software
  apt: name={{ item }}
  with_items:
    - build-essential
    - ntp
    - git
    - vim
    - emacs24
    - unzip
    - imagemagick
    - libmagick-dev
    - libxml2
    - libxml2-dev
