# Some things still require cleanup
---
- name: Apache2 | enable vhost_alias module
  apache2_module: state=present name=vhost_alias

- block:
    - command: a2dissite {{ item }}
      with_items:
        - 000-default
        - vhosts
    - service: name=apache2 state=restarted

- name: WordPress | reset ownership on WordPress installation
  file: path={{wp_install_dir}} owner=www-data group=www-data state=directory recurse=yes

- name: WordPress | Set FS_METHOD to direct
  lineinfile: dest={{ wp_install_dir }}/wp-config.php owner=www-data group=www-data state=present line='define("FS_METHOD","direct");'
